import type { EnumConfig } from '../enum-config'

/**
 * Generates a TypeScript type definition string for an enum
 *
 * @param config - Enum configuration object
 * @param values - Array of enum values
 * @returns TypeScript type definition as a string
 */
export function generateEnumDefinition(config: EnumConfig, values: string[]): string {
    return `/**
 * ${config.description}
 * 
 * Generated from: ${config.dataPath}.${config.valueField}
 * Values: ${values.join(', ')}
 * Last updated: ${new Date().toISOString()}
 */
export enum ${config.typeName} {
    ${values.map(v => `${v} = '${v}'`).join(', ')}
}
`
}

/**
 * Generates the file header comment
 *
 * @returns File header as a string
 */
export function generateFileHeader(): string {
    return `/**
 * Auto-generated type definitions for database enums
 * 
 * This file is generated by scripts/generate-enums.ts
 * Do not edit this file manually - run 'npm run generate:enums' to regenerate
 * 
 * To add new enum types, edit scripts/enum-config.ts
 * 
 * Last generated: ${new Date().toISOString()}
 */

`
}
