import './globals.css'

import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { ThemeProvider } from 'next-themes'

import Footer from '@/components/footer'
import { AppSidebar, SiteHeader } from '@/components/sidebar'
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar'
import { Toaster } from '@/components/ui/sonner'
import { createNhostClient } from '@/lib/nhost/server'
import { AuthHydration } from '@/lib/providers/auth-provider'
import { BreadcrumbsProvider } from '@/lib/providers/breadcrumbs-provider'
import QueryProvider from '@/lib/providers/query-provider'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const nhost = await createNhostClient()
    const session = nhost.getUserSession()
    const user = session?.user

    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <AuthHydration user={user} />
                <ThemeProvider attribute="class" enableSystem={true} defaultTheme="system">
                    <QueryProvider>
                        <BreadcrumbsProvider>
                            <div className="[--header-height:calc(--spacing(14))]">
                                <SidebarProvider className="flex flex-col">
                                    <SiteHeader />
                                    <div className="flex flex-1">
                                        <AppSidebar />
                                        <SidebarInset className="p-4">
                                            <div className="flex-1 min-h-screen">{children}</div>
                                            <Footer />
                                        </SidebarInset>
                                    </div>
                                </SidebarProvider>
                            </div>
                            <Toaster />
                        </BreadcrumbsProvider>
                    </QueryProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}
