/**
 * Auto-generated type definitions for database enums
 *
 * This file is generated by scripts/generate-enums.ts
 * Do not edit this file manually - run 'npm run generate:enums' to regenerate
 *
 * To add new enum types, edit scripts/enum-config.ts
 *
 * Last generated: 2025-11-05T07:53:28.726Z
 */

/**
 * Status values for tracking user movie watch progress (WATCHED, WATCHING, WATCHLIST, DROPPED)
 *
 * Generated from: user_movie_statuses.name
 * Values: WATCHED, WATCHING, WATCHLIST, DROPPED
 * Last updated: 2025-11-05T07:53:28.725Z
 */
export enum UserMovieStatus {
    WATCHED = 'WATCHED',
    WATCHING = 'WATCHING',
    WATCHLIST = 'WATCHLIST',
    DROPPED = 'DROPPED',
}

/**
 * Available gender options for people
 *
 * Generated from: genders.gender
 * Values: MALE, FEMALE, OTHER
 * Last updated: 2025-11-05T07:53:28.726Z
 */
export enum Gender {
    MALE = 'MALE',
    FEMALE = 'FEMALE',
    OTHER = 'OTHER',
}
