/**
 * Auto-generated type definitions for database enums
 *
 * This file is generated by scripts/generate-enums.ts
 * Do not edit this file manually - run 'npm run generate:enums' to regenerate
 *
 * To add new enum types, edit scripts/enum-config.ts
 *
 * Last generated: 2025-11-16T13:11:49.210Z
 */

/**
 * Available credit types
 *
 * Generated from: credit_types.credit_type
 * Values: CAST, CREW
 * Last updated: 2025-11-16T13:11:49.209Z
 */
export enum CreditType {
    CAST = 'CAST',
    CREW = 'CREW',
}

/**
 * Status values for tracking user movie watch progress (WATCHED, WATCHING, WATCHLIST, DROPPED)
 *
 * Generated from: user_movie_statuses.name
 * Values: WATCHED, WATCHING, WATCHLIST, DROPPED
 * Last updated: 2025-11-16T13:11:49.210Z
 */
export enum UserMovieStatus {
    WATCHED = 'WATCHED',
    WATCHING = 'WATCHING',
    WATCHLIST = 'WATCHLIST',
    DROPPED = 'DROPPED',
}

/**
 * Available gender options for people
 *
 * Generated from: genders.gender
 * Values: MALE, FEMALE, OTHER
 * Last updated: 2025-11-16T13:11:49.210Z
 */
export enum Gender {
    MALE = 'MALE',
    FEMALE = 'FEMALE',
    OTHER = 'OTHER',
}

/**
 * Available media types
 *
 * Generated from: media_types.name
 * Values: MOVIE, TV_SHOW, PERSON, BOOK, GAME, EPISODE, SONG
 * Last updated: 2025-11-16T13:11:49.210Z
 */
export enum MediaType {
    MOVIE = 'MOVIE',
    TV_SHOW = 'TV_SHOW',
    PERSON = 'PERSON',
    BOOK = 'BOOK',
    GAME = 'GAME',
    EPISODE = 'EPISODE',
    SONG = 'SONG',
}

/**
 * Available entity types
 *
 * Generated from: entity_types.name
 * Values: MOVIE, ACTIVITY
 * Last updated: 2025-11-16T13:11:49.210Z
 */
export enum EntityType {
    MOVIE = 'MOVIE',
    ACTIVITY = 'ACTIVITY',
}

/**
 * Available actions
 *
 * Generated from: actions.name
 * Values: INSERT, SELECT, UPDATE, DELETE
 * Last updated: 2025-11-16T13:11:49.210Z
 */
export enum Action {
    INSERT = 'INSERT',
    SELECT = 'SELECT',
    UPDATE = 'UPDATE',
    DELETE = 'DELETE',
}
